### ISSUE TITLE
G$ logo is missing when swapping in Ethereum Network

### ISSUE THREAD

**Issue by sepu85** [GoodDollar/GoodProtocolUI#127]
**Bug Description**
G$ logo is missing when swapping in Ethereum Network

**Steps to Reproduce**
1. Go to Swap
2. Connect to Ethereum Network
<img width="725" alt="Captura de pantalla 2022-01-21 a las 12 30 18" src="https://user-images.githubusercontent.com/22507864/150519804-ab9390c7-4025-47f1-946d-fd0be0d06d56.png">

**Expected Behavior**
The same G$ logo that appears on Fuse Network should appear her

**Additional Context**
N/A

**Comment by sirpy** [comment]
fixed

**Comment by sepu85** [comment]
it's not fixed on goodswap.xyz yet, can we agree on a process to update changes on the community deployed UI, please?

**Comment by sirpy** [comment]
@YpetrovAJ lets discuss that on our call next week

**Comment by artqadev** [comment]
Hi everyone :)
Verified, e.g.: 
![image.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/2f08346b-fb85-44bb-b55a-cfcf378a8783)

Thank you!

**Comment by artqadev** [comment]
Prod checked
